[theme]
primaryColor = "#4b8bbe"
backgroundColor = "#f0f0f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[general]
email = "georgiana@example.com"